name: Python Package Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pypi-publish:

    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.dev.txt
        pip install -r requirements.txt
    - name: Cache pip dependencies
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        # Check for a cache hit for the corresponding dev requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.dev.txt') }}-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: style code 
      run: |
        make style
    - name: Check code style
      run: |
        make check-style
#    - name: Check static analysis
#      run: |
#        make check-static-analysis
    - name: Install package
      run: |
        pip install .
    - name: Run unit tests
      run: |
        make test
    - name: Generate code coverage report
      run: |
        make coverage
    - name: Generate docs
      run: |
        make docs
    - name: Generate package
      run: |
        make dist
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
